name: Build and Deploy Jekyll Site at https://rusakovlab.github.io

#temporary set to manual mode, automatic on:push:branches:[master] is commented out
on: 
  workflow_dispatch:
#on:
#  push:
#    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          publish_root: true  # This option allows publishing to the root of the branch if repository is called rusakovlab.github.io
