name: Build neuroalgebra.net -> rusakovlab.github.io, artifact ZIP (for https:/neuroalgebra.net/)
on:
  push:
    branches: [master]  # Change this to your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the site in the jekyll/builder container with baseurl="/"
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # Save the _site folder as an artifact (and keep it for 1 day only)
      - name: Upload _site folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: neuroalgebra-net-ready
          path: ./_site
          retention-days: 1

      #publish to gh-pages (rusakovlab.github.io)
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          destination_dir: .

            
